### ISSUE TITLE
登录页面功能不正常

### ISSUE THREAD

**Issue by kikutou** [kikutou/workwork#5]
没有输入用户名和密码的情况下，
不提示错误。
 @luguangyun

**Comment by kikutou** [comment]
已经解决，请重新测试。

**Comment by kikutou** [comment]
OK测试完毕。
已经解决。

**Comment by maomidingdang** [comment]
CREATE TABLE `dtb_product` (
  `product_id` int(11) NOT NULL AUTO_INCREMENT,
  `product_asin` varchar(10) NOT NULL COMMENT 'amazonのASINコード',
  `product_name` text NOT NULL COMMENT '商品名',
  `product_price` int(11) NOT NULL DEFAULT '0' COMMENT
'amazonの価格、ちょび得の価格は割引率により、自動的に計算する。',
  `product_type` smallint(6) NOT NULL DEFAULT '1' COMMENT
'1:普通のプライム商品\n2:あわせ買い商品\n3:予約商品',
  `product_sale_start_date` date DEFAULT NULL COMMENT
'2:予約商品のみ、フロント側で、このフィールドの手入力が必要',
  `product_stock` smallint(6) NOT NULL DEFAULT '0' COMMENT '商品在庫状態\n0:あり
1:なし',
  `product_link` text NOT NULL COMMENT '商品リンク',
  `product_main_img_src` text COMMENT '商品メイン画像',
  `product_standard` text COMMENT
'Amazonの商品規格をstringに変更して、保存する。\n規格がある商品登録するときに、2つのやり方がある。\n①管理員は代表的な規格を入力して、他の規格と対応するASIコードを商品詳細欄に追記する。\n②管理員は親ASINコードを入力して、購入できない状態に設定する。（この場合、Amazonに親ASINコードを入力しても、検索できないため、自動入力機能も使えない。）',
  `product_description` text COMMENT '商品説明(詳細)',
  `product_assign_from` smallint(6) NOT NULL DEFAULT '0' COMMENT
'商品登録方式\n0:ユーザー検索 1:管理員登録',
  `product_shop_note` text COMMENT '商品ショップ備考',
  `product_buyable` smallint(6) NOT NULL DEFAULT '0' COMMENT '0:購入可能
1:購入できない\n在庫なしの状態で、このフラグは1購入できないようにする。',
  `del_flg` smallint(6) NOT NULL DEFAULT '0' COMMENT '0:削除しない 1:削除する',
  `create_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '作成日時',
  `create_by_admin` int(11) DEFAULT NULL COMMENT '-> メンバー情報.メンバーID    ',
  `create_by_customer` int(11) DEFAULT NULL COMMENT '-> 会員情報.会員ID    ',
  `update_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE
CURRENT_TIMESTAMP,
  `update_by_admin` int(11) DEFAULT NULL COMMENT '-> メンバー情報.メンバーID    ',
  `update_by_customer` int(11) DEFAULT NULL COMMENT '検索更新者',
  PRIMARY KEY (`product_id`),
  KEY `fk_dtb_product_1_idx` (`create_by_admin`),
  KEY `fk_dtb_product_2_idx` (`create_by_customer`),
  KEY `fk_dtb_product_3_idx` (`update_by_admin`),
  KEY `fk_dtb_product_4_idx` (`update_by_customer`),
  KEY `fk_dtb_product_5_idx` (`product_type`),
  CONSTRAINT `fk_dtb_product_1` FOREIGN KEY (`create_by_admin`) REFERENCES
`dtb_member` (`member_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_dtb_product_2` FOREIGN KEY (`create_by_customer`)
REFERENCES `dtb_customer` (`customer_id`) ON DELETE NO ACTION ON UPDATE NO
ACTION,
  CONSTRAINT `fk_dtb_product_3` FOREIGN KEY (`update_by_admin`) REFERENCES
`dtb_member` (`member_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_dtb_product_4` FOREIGN KEY (`update_by_customer`)
REFERENCES `dtb_customer` (`customer_id`) ON DELETE NO ACTION ON UPDATE NO
ACTION,
  CONSTRAINT `fk_dtb_product_5` FOREIGN KEY (`product_type`) REFERENCES
`mtb_product_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=7 DEFAULT CHARSET=utf8;


2016-09-14 12:20 GMT+09:00 kiku <notifications@github.com>:

**Comment by maomidingdang** [comment]
CREATE TABLE `dtb_product_feature` (
  `product_id` int(11) NOT NULL,
  `feature_id` int(11) NOT NULL,
  PRIMARY KEY (`product_id`,`feature_id`),
  KEY `fk_dtb_product_feature_2_idx` (`feature_id`),
  CONSTRAINT `fk_dtb_product_feature_1` FOREIGN KEY (`product_id`)
REFERENCES `dtb_product` (`product_id`) ON DELETE NO ACTION ON UPDATE NO
ACTION,
  CONSTRAINT `fk_dtb_product_feature_2` FOREIGN KEY (`feature_id`)
REFERENCES `dtb_feature` (`feature_id`) ON DELETE NO ACTION ON UPDATE NO
ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


2016-10-14 20:12 GMT+09:00 柳若婷 <maomidingdang007@gmail.com>:

**Comment by maomidingdang** [comment]
CREATE TABLE `dtb_feature` (
  `feature_id` int(11) NOT NULL AUTO_INCREMENT,
  `feature_name` text NOT NULL,
  `feature_main_img_src` text CHARACTER SET latin1,
  `feature_description` text CHARACTER SET latin1,
  `feature_start_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `feature_end_time` datetime NOT NULL DEFAULT '2036-12-31 23:59:59',
  `del_flg` smallint(6) NOT NULL DEFAULT '0',
  `create_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `create_by` int(11) NOT NULL,
  `update_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE
CURRENT_TIMESTAMP,
  `update_by` int(11) NOT NULL,
  PRIMARY KEY (`feature_id`),
  KEY `fk_dtb_feature_1_idx` (`create_by`),
  KEY `fk_dtb_feature_2_idx` (`update_by`),
  CONSTRAINT `fk_dtb_feature_1` FOREIGN KEY (`create_by`) REFERENCES
`dtb_member` (`member_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_dtb_feature_2` FOREIGN KEY (`update_by`) REFERENCES
`dtb_member` (`member_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=4 DEFAULT CHARSET=utf8;


2016-10-14 20:17 GMT+09:00 柳若婷 <maomidingdang007@gmail.com>:

**Comment by maomidingdang** [comment]
CREATE TABLE `dtb_product_image` (
  `product_image_id` int(11) NOT NULL,
  `product_id` int(11) NOT NULL,
  `product_image_src` text NOT NULL,
  `del_flg` smallint(6) NOT NULL COMMENT '0:削除しない 1:削除する',
  `create_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`product_image_id`),
  KEY `fk_dtb_product_image_1` (`product_id`),
  CONSTRAINT `fk_dtb_product_image_1` FOREIGN KEY (`product_image_id`)
REFERENCES `dtb_product` (`product_id`) ON DELETE NO ACTION ON UPDATE NO
ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


2016-10-14 20:19 GMT+09:00 柳若婷 <maomidingdang007@gmail.com>:

**Comment by maomidingdang** [comment]
CREATE TABLE `dtb_feature_image` (
  `feature_image_id` int(11) NOT NULL AUTO_INCREMENT,
  `feature_id` int(11) NOT NULL,
  `feature_image_src` text NOT NULL,
  `del_flg` smallint(6) NOT NULL DEFAULT '0',
  `created_date` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE
CURRENT_TIMESTAMP,
  PRIMARY KEY (`feature_image_id`),
  KEY `fk_dtb_feature_image_1_idx` (`feature_id`),
  CONSTRAINT `fk_dtb_feature_image_1` FOREIGN KEY (`feature_id`) REFERENCES
`dtb_feature` (`feature_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


2016-10-14 20:21 GMT+09:00 柳若婷 <maomidingdang007@gmail.com>:

**Comment by maomidingdang** [comment]
CREATE TABLE `dtb_product_image` (
  `product_image_id` int(11) NOT NULL,
  `product_id` int(11) NOT NULL,
  `product_image_src` text NOT NULL,
  `del_flg` smallint(6) NOT NULL COMMENT '0:削除しない 1:削除する',
  `create_date` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`product_image_id`),
  KEY `fk_dtb_product_image_1` (`product_id`),
  CONSTRAINT `fk_dtb_product_image_1` FOREIGN KEY (`product_image_id`)
REFERENCES `dtb_product` (`product_id`) ON DELETE NO ACTION ON UPDATE NO
ACTION
) ENGINE=InnoDB DEFAULT CHARSET=latin1;


2016-10-14 20:24 GMT+09:00 柳若婷 <maomidingdang007@gmail.com>:

**Comment by maomidingdang** [comment]
product_standard` longtext COMMENT
'Amazonの商品規格をstringに変更して、保存する。\n規格がある商品登録するときに、2つのやり方がある。\n①管理員は代表的な規格を入力して、他の規格と対応するASIコードを商品詳細欄に追記する。\n②管理員は親ASINコードを入力して、購入できない状態に設定する。（この場合、Amazonに親ASINコードを入力しても、検索できないため、自動入力機能も使えない。）',

2016-10-14 20:25 GMT+09:00 柳若婷 <maomidingdang007@gmail.com>:

**Comment by maomidingdang** [comment]
購入可能 1:購入できない\n在庫なしの状態で、このフラグは1購入できないようにする。'

2016-10-14 20:43 GMT+09:00 柳若婷 <maomidingdang007@gmail.com>:

**Comment by maomidingdang** [comment]
PRIMARY KEY (`product_id`),
  UNIQUE KEY `product_asin_UNIQUE` (`product_asin`),
  KEY `fk_dtb_product_1_idx` (`product_type`),
  KEY `fk_dtb_product_2_idx` (`create_by_admin`),
  KEY `fk_dtb_product_3_idx` (`create_by_customer`),
  KEY `fk_dtb_product_4_idx` (`update_by_admin`),
  KEY `fk_dtb_product_5_idx` (`update_by_customer`),
  CONSTRAINT `fk_dtb_product_1` FOREIGN KEY (`product_type`) REFERENCES
`mtb_product_type` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_dtb_product_2` FOREIGN KEY (`create_by_admin`) REFERENCES
`dtb_member` (`member_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_dtb_product_3` FOREIGN KEY (`create_by_customer`)
REFERENCES `dtb_customer` (`customer_id`) ON DELETE NO ACTION ON UPDATE NO
ACTION,
  CONSTRAINT `fk_dtb_product_4` FOREIGN KEY (`update_by_admin`) REFERENCES
`dtb_member` (`member_id`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `fk_dtb_product_5` FOREIGN KEY (`update_by_customer`)
REFERENCES `dtb_customer` (`customer_id`) ON DELETE NO ACTION ON UPDATE NO
ACTION

2016-10-14 20:45 GMT+09:00 柳若婷 <maomidingdang007@gmail.com>:

**Comment by maomidingdang** [comment]
ALTER TABLE `miao`.`dtb_product`





ADD CONSTRAINT `fk_dtb_product_1`





FOREIGN KEY (`created_by_admin`)





REFERENCES `miao`.`dtb_member` (`member_id`)





ON DELETE NO ACTION





ON UPDATE NO ACTION,





ADD CONSTRAINT `fk_dtb_product_2`





FOREIGN KEY (`created_by_customer`)





REFERENCES `miao`.`dtb_customer` (`customer_id`)





ON DELETE NO ACTION





ON UPDATE NO ACTION;












ALTER TABLE `miao`.`dtb_product`





ADD INDEX `fk_dtb_product_3_idx` (`updater_admin` ASC) COMMENT '',





ADD INDEX `fk_dtb_product_4_idx` (`updater_customer` ASC) COMMENT '';





ALTER TABLE `miao`.`dtb_product`





ADD CONSTRAINT `fk_dtb_product_3`





FOREIGN KEY (`updater_admin`)





REFERENCES `miao`.`dtb_member` (`member_id`)





ON DELETE NO ACTION





ON UPDATE NO ACTION,





ADD CONSTRAINT `fk_dtb_product_4`





FOREIGN KEY (`updater_customer`)





REFERENCES `miao`.`dtb_customer` (`customer_id`)





ON DELETE NO ACTION





ON UPDATE NO ACTION;






2016-10-14 20:53 GMT+09:00 柳若婷 <maomidingdang007@gmail.com>:
